export const UI = {
  buttons: {
    save: "Guardar peça",
    saveChanges: "Guardar canvis",
    delete: "Eliminar",
    close: "Tancar",
    clearFilters: "Netejar filtres",
    edit: "Editar",
  },
  form: {
    category: "Categoria",
    colors: "Colors",
    texture: "Textura",
    pattern: "Dibuix",
    seasons: "Temporada",
    size: "Talla",
    subtype: "Tipus",
    length: "Llargada",
    fit: "Tall",
    notes: "Notes",
    required: "*",
  },
  errors: {
    requiredFields: "Omple tots els camps marcats amb *",
    minOneSeason: "Selecciona almenys una temporada",
    minOneColor: "Selecciona almenys un color",
    invalidColor: "Color no valid",
  },
  modal: {
    texture: "Textura",
    pattern: "Dibuix",
    colors: "Colors",
    seasons: "Temporada",
    notes: "Notes",
  },
  grid: {
    filters: "Filtres",
    categories: "Categoria",
    seasons: "Temporada",
    fits: "Tall",
    textures: "Textura",
    noResults: "Cap peça trobada",
    results: (count: number) => `${count} peça${count !== 1 ? "s" : ""}`,
  },
  bugaderia: {
    title: "bugaderia",
    subtitle: "què tens net, què tens al cistell, i què et pots posar avui.",
    soil: "Embrutar",
    wash: "Rentar",
    today: "Què em poso?",
    cleanCount: (n: number) => (n === 1 ? "1 peça neta" : `${n} peces netes`),
    basketCount: (n: number) =>
      n === 1 ? "1 peça al cistell" : `${n} peces al cistell`,
    readyCount: (n: number) => (n === 1 ? "1 outfit a punt" : `${n} outfits a punt`),
  },
} as const;
