export const UI = {
  buttons: {
    save: "Guardar peça",
    saveChanges: "Guardar canvis",
    delete: "Eliminar",
    close: "Tancar",
    clearFilters: "Netejar filtres",
    edit: "Editar",
  },
  form: {
    category: "Categoria",
    colors: "Colors",
    texture: "Textura",
    pattern: "Dibuix",
    seasons: "Temporada",
    size: "Talla",
    subtype: "Tipus",
    length: "Llargada",
    fit: "Tall",
    notes: "Notes",
    required: "*",
  },
  errors: {
    requiredFields: "Omple tots els camps marcats amb *",
    minOneSeason: "Selecciona almenys una temporada",
    minOneColor: "Selecciona almenys un color",
    invalidColor: "Color no valid",
  },
  modal: {
    texture: "Textura",
    pattern: "Dibuix",
    colors: "Colors",
    seasons: "Temporada",
    notes: "Notes",
  },
  grid: {
    filters: "Filtres",
    categories: "Categoria",
    seasons: "Temporada",
    fits: "Tall",
    textures: "Textura",
    noResults: "Cap peça trobada",
    results: (count: number) => `${count} peça${count !== 1 ? "s" : ""}`,
  },
  bugaderia: {
    title: "bugaderia",
    subtitle: "què tens net, què tens al cistell, i què et pots posar avui.",
    soil: "Embrutar",
    wash: "Rentar",
    today: "Què em poso?",
    cleanCount: (n: number) => (n === 1 ? "1 peça neta" : `${n} peces netes`),
    basketCount: (n: number) =>
      n === 1 ? "1 peça al cistell" : `${n} peces al cistell`,
    readyCount: (n: number) => (n === 1 ? "1 outfit a punt" : `${n} outfits a punt`),
    picker: {
      soil: {
        title: "Embrutar",
        subtitle: "tria les peces que van al cistell.",
        submit: "Marcar com a brut",
        submitting: "marcant…",
        toast: (n: number) => (n === 1 ? "1 peça al cistell" : `${n} peces al cistell`),
        empty: "totes les peces ja són al cistell.",
      },
      wash: {
        title: "Rentar",
        subtitle: "tria les peces que has rentat.",
        submit: "Marcar com a net",
        submitting: "marcant…",
        toast: (n: number) => (n === 1 ? "1 peça neta" : `${n} peces netes`),
        empty: "cap peça al cistell. tot net.",
        didLaundry: "he fet la bugada",
      },
      selectedCount: (n: number) => (n === 1 ? "1 seleccionada" : `${n} seleccionades`),
      clearSelection: "desmarcar-ho tot",
    },
    avui: {
      wearIt: "Me'l poso",
      almost: "gairebé",
      almostMissing: (label: string) => `et falta: ${label}`,
      wornToday: "portat avui",
      alreadyToday: "ja portes un altre outfit avui. tornar-lo a triar el substituirà.",
      emptyNoOutfits: "encara no tens outfits desats",
      emptyNoneReady: "toca fer bugada",
      goToArmari: "anar a l'armari",
      goToRentar: "anar a rentar",
    },
    grid: {
      state: "Estat",
      clean: "Netes",
      dirty: "Brutes",
      badge: "al cistell",
    },
  },
} as const;
